use [top_music]

CREATE TABLE genre
(
id BIGINT PRIMARY KEY IDENTITY,
genre VARCHAR(50) NOT NULL,
)

CREATE TABLE author
(
id BIGINT PRIMARY KEY IDENTITY,
au_name VARCHAR(50) NOT NULL,
au_surname VARCHAR(50) NOT NULL,
au_pseudo VARCHAR(50) NOT NULL,
)

CREATE TABLE band
(
id BIGINT PRIMARY KEY IDENTITY,
band_name VARCHAR(50) NOT NULL,
creation_date DATETIME NOT NULL,
)

CREATE TABLE song
(
id BIGINT PRIMARY KEY IDENTITY,
song_name VARCHAR(50) NOT NULL,
duration TIME(7) NOT NULL,
genre_id BIGINT NOT NULL,
author_id BIGINT NOT NULL,
band_id BIGINT NOT NULL,
CONSTRAINT FK_genre FOREIGN KEY (genre_id) REFERENCES genre (id) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_author FOREIGN KEY (author_id) REFERENCES author (id) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_band_author FOREIGN KEY (band_id) REFERENCES band (id) ON UPDATE CASCADE ON DELETE NO ACTION,
)

CREATE TABLE artist_role
(
id BIGINT PRIMARY KEY IDENTITY,
role_name VARCHAR(50) NOT NULL,
)

CREATE TABLE artist
(
id BIGINT PRIMARY KEY IDENTITY,
band_id BIGINT,
art_name VARCHAR(50) NOT NULL,
art_surname VARCHAR(50) NOT NULL,
art_pseudo VARCHAR(50) NOT NULL,
role_id BIGINT NOT NULL,
CONSTRAINT FK_band_artist FOREIGN KEY (band_id) REFERENCES artist (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT FK_role FOREIGN KEY (role_id) REFERENCES artist_role (id) ON UPDATE CASCADE ON DELETE NO ACTION,

)

CREATE TABLE top_type
(
id BIGINT PRIMARY KEY IDENTITY,
top_name VARCHAR(50) NOT NULL,
)

CREATE TABLE song_top
(
id_song BIGINT UNIQUE NOT NULL,
id_top BIGINT UNIQUE NOT NULL,
place BIGINT NOT NULL,
date_of_release DATETIME NOT NULL,
PRIMARY KEY(id_song,id_top) ,
CONSTRAINT FK_song FOREIGN KEY (id_song) REFERENCES song (id) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_top FOREIGN KEY (id_top) REFERENCES top_type (id) ON UPDATE CASCADE ON DELETE NO ACTION
)